spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: nhatcoi
    password: nhatcoi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  fly-way:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "initial"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8080
