##

services:
  postgres:
    image: postgres
    container_name: ms_pg_sql
    environment:
      POSTGRES_USER: nhatcoi
      POSTGRES_PASSWORD: nhatcoi
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: ms_pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: ms_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nhatcoi
      - MONGO_INITDB_ROOT_PASSWORD=nhatcoi
    networks:
      - microservices-net
      
  mongo-express:
    image: mongo-express
    container_name: ms_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=nhatcoi
      - ME_CONFIG_MONGODB_ADMINPASSWORD=nhatcoi
      - ME_CONFIG_MONGODB_URL=mongodb://nhatcoi:nhatcoi@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=nhatcoi
      - ME_CONFIG_BASICAUTH_PASSWORD=nhatcoi
    depends_on:
      - mongodb
    networks:
      - microservices-net

  mail-dev:
    image: maildev/maildev
    container_name: ms_mail_dev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices-net


networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: